### ISSUE TITLE
Broken image links 

### ISSUE THREAD

**Issue by yrabbit** [syd711/mephisto_fx#4]
Hello,
http://syd711.github.io/mephisto_i/ http://syd711.github.io/mephisto_ii/ and http://syd711.github.io/mephisto_fx/ nave no single image displayed.

That's sad because I really want to see the photos.

**Comment by syd711** [comment]
Ah, thanks for the hint. I accidently misconfigured the server a week ago.
All images, except the YouTube video are online again.

**Comment by yrabbit** [comment]
Thanks:)
